services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - restaurants_network
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - restaurants_network
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:

networks:
  restaurants_network:
    driver: bridge